on:
  push:
    tags:
      - '*'
jobs:
  make-ipxe:
    name: create iso
    runs-on: self-hosted
    steps:
      - name: delete old files
        run: |
           sudo rm -rf ${GITHUB_WORKSPACE}/self
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
      - name: build iso
        run: |
           self/create-custom-archlinux-iso.sh
      - name: create and upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{github.workspace}}/self/output/assistance.iso
          token: ${{ secrets.GITHUB_TOKEN }}

