on: [push]
jobs:
  make-ipxe:
    name: make ipxe
    runs-on: self-hosted
    steps:
      - name: delete old folder
        run: |
           sudo rm -rf ${GITHUB_WORKSPACE}/self
      - name: checkout self/this
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
      - name: install dependencies
        run: |
           self/create-custom-archlinux-iso.sh
      - name: upload ISO as artifact
        uses: actions/upload-artifact@v2
        with:
          name: assistance.iso
          path: ${GITHUB_WORKSPACE}/self/output/arch-custom.iso
