on: [push]
jobs:
  make-ipxe:
    name: create iso
    runs-on: self-hosted
    steps:
      - name: delete old files
        run: |
           echo "${GITHUB_WORKSPACE}"
           sudo rm -rf ${GITHUB_WORKSPACE}/self
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
      - name: echo workspace
        run: |
           echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
           echo "github.workspace ${{github.workspace}}"
      - name: build iso
        run: |
           self/create-custom-archlinux-iso.sh
      - name: upload ISO as artifact
        uses: actions/upload-artifact@v2
        with:
          name: assistance.iso
          path: ${{github.workspace}}/self/output/assistance.iso
