on: [push]
jobs:
  make-ipxe:
    name: make ipxe
    runs-on: archlinux
    container: docker://archlinux
    steps:
      - name: checkout self/this
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
