on:
  push:
    tags:
      - '*'
jobs:
  make-ipxe:
    name: create iso
    runs-on: self-hosted
    steps:
      - name: delete old files
        run: |
           sudo rm -rf ${GITHUB_WORKSPACE}/self
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
      - name: build iso
        run: |
           self/create-custom-archlinux-iso.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/self/output/assistance.iso
          asset_name: assistance.iso
          tag: ${{ github.ref }}
          overwrite: true
          body: "Helpdesk Bootable Linux ISO with Teamviewer"
