on:
  push:
    tags:
      - '*'
jobs:
  make-ipxe:
    name: create iso
    runs-on: self-hosted
    steps:
      - name: delete old files
        run: |
           sudo rm -rf ${GITHUB_WORKSPACE}/self
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
      - name: build iso
        run: |
           self/create-custom-archlinux-iso.sh
      - name: Create release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{github.workspace}}/self/output/assistance.iso
          verbose: true
