on: [push]
jobs:
  make-ipxe:
    name: make ipxe
    runs-on: self-hosted
    container: docker://archlinux
      options: --privileged
    steps:
      - name: checkout self/this
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: self
      - name: install dependencies
        run: |
           self/create-custom-archlinux-iso.sh
